services:
  dl-service:
    build:
      context: ../dl-services
      dockerfile: Dockerfile
    container_name: dl-service-1
    volumes:
      - "D:/MyData/Disk D/Mel_luoi/project/vqa-models:/app/models"
      - "D:/MyData/Disk D/Mel_luoi/project/vqa-models/tinyllama:/app/models/tinyllama"
    environment:
      - HF_HOME=/app/models/hf
      - YOLOV8_MODEL_PATH=/app/models/yolov8n.pt
      - TINYBLIP_MODEL_ID=Salesforce/blip-image-captioning-base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
    networks:
      - vqa-net

  server-backend:
    build:
      context: ../server-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DL_SERVICE_URL=http://dl-service:8000
    networks:
      - vqa-net
    depends_on:
      - dl-service

networks:
  vqa-net:
    driver: bridge
