FROM python:3.10-slim

WORKDIR /app

# Cài đặt các gói Python, torch CPU lấy từ pytorch.org
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

# Copy code
COPY ./services ./services
COPY ./routers ./routers
COPY ./main.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]