# Giai đoạn build
FROM maven:3.8.7-openjdk-18-slim AS build
WORKDIR /app

# Chỉ copy pom.xml trước để cache dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code và build
COPY src ./src
RUN mvn package -DskipTests

# Giai đoạn chạy
FROM openjdk:18-slim
WORKDIR /app

# Copy file jar từ giai đoạn build
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]