FROM python:3.10-slim

WORKDIR /app

# Cài torch CPU (hoặc GPU nếu có NVIDIA Container Toolkit)
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./services ./services
COPY ./routers ./routers
COPY ./main.py .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]