version: '3.8'

services:
  dl-service:
    build:
      context: ../dl-services
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - vqa-net

  server-backend:
    build:
      context: ../server-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DL_SERVICE_URL=http://dl-service:8000
    networks:
      - vqa-net
    depends_on:
      - dl-service

networks:
  vqa-net:
    driver: bridge